config/routes.rb
Rails.application.routes.draw do
  resources :attendances do
    post :gowing_leaving_work, on: :member
  end  
  resources :users do
    member do
      get :attendances_edit
      patch :attendance_update
     
    end  
  end  
  root "users#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :attendances, dependent: :destroy

    def serchDay(first, last)
        self.attendances.where(worked_on: first .. last).order(id: :ASC)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: 'Attendance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def gowing_leaving_work
    attendance = Attendance.find( params[:id])
    user = attendance.user
    t = Time.new
    if attendance.start.nil?
      attendance.update_attributes(
        start: Time.now
      )
    elsif attendance.finish.nil?  
      attendance.update_attributes(
        finish: Time.now
      )
    end
    redirect_to user_url(user, params:{day: params[:day]})
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendance_params
      params.require(:attendance).permit(:worked_on, :start, :finish)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :attendances_edit, :attendance_update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if params[:day].present?
      @sixteen_day = Date.parse( params[:day] )
    else
      first_day = Date.today.beginning_of_month
      @sixteen_day = first_day + 15
    end    
    @next_fifteenth_day = @sixteen_day.beginning_of_month.next_month + 14 
    (@sixteen_day .. @next_fifteenth_day).each do |day|
       unless @user.attendances.any?{|attendance| attendance.worked_on == day}
         record = @user.attendances.build(worked_on: day)
         record.save
       end 
    end
    @days = @user.serchDay(@sixteen_day, @next_fifteenth_day)
    @week = %w(日 月 火 水 木 金 土)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def attendances_edit
    @sixteen_day = Date.parse( params[:day] )
    @next_fifteenth_day = @sixteen_day.beginning_of_month.next_month + 14 
    @days = @user.serchDay(@sixteen_day, @next_fifteenth_day)
    @week = %w(日 月 火 水 木 金 土)
  end

  def attendance_update
    attendance_params.each do |id, item|
      attendance = Attendance.find id
      attendance.update_attributes(item)
    end  
    redirect_to user_url(@user, params:{day: params[:day]})
  end
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
    def attendance_params
      params.require(:user).permit(attendances:[ :start, :finish])[:attendances]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/_form.html.erb
<%= form_with(model: attendance, local: true) do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :worked_on %>
    <%= form.date_select :worked_on %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.datetime_select :start %>
  </div>

  <div class="field">
    <%= form.label :finish %>
    <%= form.datetime_select :finish %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendances</h1>

<table>
  <thead>
    <tr>
      <th>Worked on</th>
      <th>Start</th>
      <th>Finish</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.worked_on %></td>
        <td><%= attendance.start %></td>
        <td><%= attendance.finish %></td>
        <td><%= link_to 'Show', attendance %></td>
        <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
        <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance', new_attendance_path %>

app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Worked on:</strong>
  <%= @attendance.worked_on %>
</p>

<p>
  <strong>Start:</strong>
  <%= @attendance.start %>
</p>

<p>
  <strong>Finish:</strong>
  <%= @attendance.finish %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.2/xlsx.full.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/attendances_edit.html.erb
<div class="text-center"><h1>勤怠編集</h1></div>
<div class="row">
　<div class="col-md-8 offset-2 bg-light shadow p-5">
   
   <%= form_with model: @user, url:attendance_update_user_path(@user, params:{day: @sixteen_day}), local: true, method: :patch do |f| %>
    <table class="table table-bordered">
     <thead>
      <tr>
        <th  class="text-center bg-white align-middle">日付</th>
        <th  class="text-center bg-white align-middle">曜日</th>
        <th  class="text-center bg-white">出勤時間</th>
        <th  class="text-center bg-white">退勤時間</th>
      </tr>
     
     </thead>
     <tbody>
       <% @days.each do |day| %>
        <%= f.fields_for "attendances[]", day do |af| %>
       <tr>
         <td class="text-center bg-white"><%= l day.worked_on, format: :short %></td>
         <td class="text-center bg-white"><%= @week[day.worked_on.wday] %></td>
         <td><%= af.time_field :start, class: "form-control" if day.worked_on  <= Date.today %></td>
         <td><%= af.time_field :finish, class: "form-control" if day.worked_on  <= Date.today %></td>
       </tr>
       <% end %>
      <% end %>
     </tbody>
    </table>
    <div class="text-center">
      <%= link_to "戻る", user_path(@user,params:{day:@sixteen_day}), class: "btn btn-secondary" %>
      <%= f.submit "編集", class:"btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="text-center"><h1>勤怠</h1></div>
<div class="row">
　<div class="col-md-8 offset-2 bg-light shadow p-5">
    <table class="mb-2">
      <tr>
        <td><%= link_to "←", user_path(@user, params:{day: @sixteen_day.prev_month}), class:"btn btn-primary mr-2" %></td>
        <td><%= link_to "→", user_path(@user, params:{day: @sixteen_day.next_month}), class:"btn btn-primary mr-5" %></td>
        <td><%= link_to "編集", attendances_edit_user_path(@user,params:{day:  @sixteen_day}), class:"btn btn-primary" %></td>
        <td><input type="button" id="xlsx" value="Excel出力" class="btn btn-success" onclick="func1()"></td>
      </tr>
    </table>


    <table class="table table-bordered">
     <thead>
      <tr>
        <th rowspan="2" class="text-center bg-white align-middle">日付</th>
        <th rowspan="2" class="text-center bg-white align-middle">曜日</th>
        <th colspan="3" class="text-center bg-white">出勤時間</th>
        <th colspan="3" class="text-center bg-white">退勤時間</th>
      </tr>
      <tr>
         <th class="text-center bg-white">時</th>
         <th class="text-center bg-white">分</th>
         <th class="text-center bg-white"></th>
  
         <th class="text-center bg-white">時</th>
         <th class="text-center bg-white">分</th>
         <th class="text-center bg-white"></th>
      </tr>
     </thead>
     <tbody>
      <% @days.each do |day| %>
       <tr>
         <td class="text-center bg-white"><%= l day.worked_on, format: :short %></td>
         <td class="text-center bg-white"><%= @week[day.worked_on.wday] %></td>
         <td class="text-center bg-white"><%= l day.start, format: :hour if day.start.present? %></td>
         <td class="text-center bg-white"><%= l day.start, format: :min if day.start.present? %></td>
         <td class="text-center bg-white">
           <% if day.worked_on == Date.today && day.start.nil? %>
            <%= button_to '出勤', gowing_leaving_work_attendance_path(day,params:{day:  @sixteen_day}), class: 'btn btn-success btn-block' %>
           <% end %>
         </td>
         <td class="text-center bg-white"><%= l day.finish, format: :hour if day.finish.present? %></td>
         <td class="text-center bg-white"><%= l day.finish, format: :min if day.finish.present? %></td>
         <td class="text-center bg-white">
           <% if day.worked_on == Date.today && day.start.present? && day.finish.nil? %>
            <%= button_to '退勤', gowing_leaving_work_attendance_path(day,params:{day:  @sixteen_day}), class: 'btn btn-success btn-block' %>
           <% end %>
         </td>
       </tr>
      <% end %>
     </tbody>
    </table>
  </div>
</div>